
import React from 'react';
import { Listing, User, Amenity } from './types';

export const AMENITIES: Amenity[] = [
  { id: 'wifi', name: 'Fast WiFi', icon: '📶' },
  { id: 'kitchen', name: 'Kitchen', icon: '🍳' },
  { id: 'pool', name: 'Pool', icon: '🏊' },
  { id: 'parking', name: 'Free Parking', icon: '🚗' },
  { id: 'ac', name: 'Air Conditioning', icon: '❄️' },
  { id: 'workspace', name: 'Dedicated Workspace', icon: '💻' },
  { id: 'gym', name: 'Gym', icon: '💪' },
  { id: 'beach', name: 'Beachfront', icon: '🏖️' },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    role: 'HOST',
    profileImage: 'https://picsum.photos/seed/u1/200',
    bio: 'Lover of travel and architecture. Hosting unique stays since 2018.',
    isVerified: true,
    joinedDate: '2018-05-12',
  },
  {
    id: 'u2',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    role: 'GUEST',
    profileImage: 'https://picsum.photos/seed/u2/200',
    isVerified: true,
    joinedDate: '2020-01-15',
  }
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1',
    hostId: 'u1',
    title: 'Ombak Laut',
    description: 'Experience the serene beauty of Pulau Perhentian. This beachfront challet offers crystal clear waters and white sandy beaches right at your doorstep.',
    pricePerNight: 450,
    type: 'ENTIRE_HOME',
    location: {
      address: 'Long Beach',
      city: 'Pulau Perhentian',
      country: 'Malaysia',
      lat: 5.9167,
      lng: 102.7333,
    },
    images: [
      'https://picsum.photos/seed/malaysia1/800/600',
      'https://picsum.photos/seed/malaysia1b/800/600',
      'https://picsum.photos/seed/malaysia1c/800/600',
    ],
    amenities: ['wifi', 'beach', 'ac', 'parking'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rating: 4.95,
    reviewCount: 128,
    reviews: [
      {
        id: 'r1',
        userId: 'u2',
        userName: 'Sarah Chen',
        userImage: 'https://picsum.photos/seed/u2/100',
        rating: 5,
        comment: 'Absolutely stunning. Best stay of my life!',
        date: '2023-11-20'
      }
    ],
    houseRules: ['No smoking', 'No pets', 'No parties'],
  },
  {
    id: 'l2',
    hostId: 'u1',
    title: 'Ombak Rindu',
    description: 'A cozy retreat in Cherating, famous for its surfing culture and laid-back vibe. Perfect for a relaxing weekend getaway.',
    pricePerNight: 280,
    type: 'ENTIRE_HOME',
    location: {
      address: 'Cherating Beach',
      city: 'Kuantan',
      country: 'Malaysia',
      lat: 4.1257,
      lng: 103.3892,
    },
    images: [
      'https://picsum.photos/seed/malaysia2/800/600',
      'https://picsum.photos/seed/malaysia2b/800/600',
      'https://picsum.photos/seed/malaysia2c/800/600',
    ],
    amenities: ['wifi', 'kitchen', 'beach', 'parking', 'ac'],
    maxGuests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    rating: 4.88,
    reviewCount: 64,
    reviews: [],
    houseRules: ['Quiet hours after 10 PM'],
  },
  {
    id: 'l3',
    hostId: 'u1',
    title: 'Ombak Rasa',
    description: 'Luxury living in Langkawi. Enjoy the legendary sunset and duty-free shopping while staying in this premium suite.',
    pricePerNight: 650,
    type: 'ENTIRE_HOME',
    location: {
      address: 'Pantai Cenang',
      city: 'Langkawi',
      country: 'Malaysia',
      lat: 6.2926,
      lng: 99.7288,
    },
    images: [
      'https://picsum.photos/seed/malaysia3/800/600',
      'https://picsum.photos/seed/malaysia3b/800/600',
    ],
    amenities: ['wifi', 'kitchen', 'pool', 'ac'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rating: 4.90,
    reviewCount: 245,
    reviews: [],
    houseRules: ['No outdoor shoes inside'],
  },
  {
    id: 'l4',
    hostId: 'u1',
    title: 'Modern A-Frame Cabin with Hot Tub',
    description: 'The perfect getaway for couples. Enjoy stargazing from the hot tub or roasting marshmallows by the fire pit.',
    pricePerNight: 280,
    type: 'ENTIRE_HOME',
    location: {
      address: 'Mountain Top Rd',
      city: 'Lake Tahoe',
      country: 'USA',
      lat: 39.0968,
      lng: -120.0324,
    },
    images: [
      'https://picsum.photos/seed/l4a/800/600',
      'https://picsum.photos/seed/l4b/800/600',
    ],
    amenities: ['wifi', 'kitchen', 'parking', 'ac'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.98,
    reviewCount: 89,
    reviews: [],
    houseRules: ['Leave the space as you found it'],
  },
  {
    id: 'l5',
    hostId: 'u1',
    title: 'Minimalist Tokyo Studio',
    description: 'Clean, efficient, and perfectly located. Experience the best of Shibuya from this quiet sanctuary.',
    pricePerNight: 85,
    type: 'ENTIRE_HOME',
    location: {
      address: 'Shibuya-ku',
      city: 'Tokyo',
      country: 'Japan',
      lat: 35.6762,
      lng: 139.6503,
    },
    images: [
      'https://picsum.photos/seed/l5a/800/600',
    ],
    amenities: ['wifi', 'ac', 'workspace'],
    maxGuests: 2,
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    rating: 4.65,
    reviewCount: 156,
    reviews: [],
    houseRules: ['No trash left behind'],
  }
];
