
import React from 'react';
import { Listing, User, Amenity } from './types';

export const AMENITIES: Amenity[] = [
  { id: 'wifi', name: 'Fast WiFi', icon: '📶' },
  { id: 'kitchen', name: 'Kitchen', icon: '🍳' },
  { id: 'pool', name: 'Pool', icon: '🏊' },
  { id: 'parking', name: 'Free Parking', icon: '🚗' },
  { id: 'ac', name: 'Air Conditioning', icon: '❄️' },
  { id: 'workspace', name: 'Dedicated Workspace', icon: '💻' },
  { id: 'gym', name: 'Gym', icon: '💪' },
  { id: 'beach', name: 'Beachfront', icon: '🏖️' },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    role: 'HOST',
    profileImage: 'https://picsum.photos/seed/u1/200',
    bio: 'Lover of travel and architecture. Hosting unique stays since 2018.',
    isVerified: true,
    joinedDate: '2018-05-12',
  },
  {
    id: 'u2',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    role: 'GUEST',
    profileImage: 'https://picsum.photos/seed/u2/200',
    isVerified: true,
    joinedDate: '2020-01-15',
  }
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1',
    hostId: 'u1',
    title: 'Modern Architectural Marvel in the Woods',
    description: 'Experience true luxury in this award-winning glass house. Surrounded by ancient pines, this home offers floor-to-ceiling views of nature.',
    pricePerNight: 450,
    type: 'ENTIRE_HOME',
    location: {
      address: '123 Forest Lane',
      city: 'Aspen',
      country: 'USA',
      lat: 39.1911,
      lng: -106.8175,
    },
    images: [
      'https://picsum.photos/seed/l1a/800/600',
      'https://picsum.photos/seed/l1b/800/600',
      'https://picsum.photos/seed/l1c/800/600',
    ],
    amenities: ['wifi', 'kitchen', 'parking', 'ac', 'workspace'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rating: 4.95,
    reviewCount: 128,
    reviews: [
      {
        id: 'r1',
        userId: 'u2',
        userName: 'Sarah Chen',
        userImage: 'https://picsum.photos/seed/u2/100',
        rating: 5,
        comment: 'Absolutely stunning. Best stay of my life!',
        date: '2023-11-20'
      }
    ],
    houseRules: ['No smoking', 'No pets', 'No parties'],
  },
  {
    id: 'l2',
    hostId: 'u1',
    title: 'Tropical Beachfront Villa with Private Pool',
    description: 'Step directly onto the sand from your living room. This private villa offers unparalleled access to the ocean and a secluded infinity pool.',
    pricePerNight: 850,
    type: 'ENTIRE_HOME',
    location: {
      address: '45 Marine Drive',
      city: 'Bali',
      country: 'Indonesia',
      lat: -8.4095,
      lng: 115.1889,
    },
    images: [
      'https://picsum.photos/seed/l2a/800/600',
      'https://picsum.photos/seed/l2b/800/600',
      'https://picsum.photos/seed/l2c/800/600',
    ],
    amenities: ['wifi', 'kitchen', 'pool', 'parking', 'ac', 'beach'],
    maxGuests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3.5,
    rating: 4.88,
    reviewCount: 64,
    reviews: [],
    houseRules: ['Quiet hours after 10 PM'],
  },
  {
    id: 'l3',
    hostId: 'u1',
    title: 'Cozy Loft in the Heart of Paris',
    description: 'Live like a local in this beautifully renovated 18th-century loft. Walking distance to the Louvre and the Seine.',
    pricePerNight: 120,
    type: 'PRIVATE_ROOM',
    location: {
      address: '12 Rue de Rivoli',
      city: 'Paris',
      country: 'France',
      lat: 48.8566,
      lng: 2.3522,
    },
    images: [
      'https://picsum.photos/seed/l3a/800/600',
      'https://picsum.photos/seed/l3b/800/600',
    ],
    amenities: ['wifi', 'kitchen', 'workspace'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.75,
    reviewCount: 245,
    reviews: [],
    houseRules: ['No outdoor shoes inside'],
  },
  {
    id: 'l4',
    hostId: 'u1',
    title: 'Modern A-Frame Cabin with Hot Tub',
    description: 'The perfect getaway for couples. Enjoy stargazing from the hot tub or roasting marshmallows by the fire pit.',
    pricePerNight: 280,
    type: 'ENTIRE_HOME',
    location: {
      address: 'Mountain Top Rd',
      city: 'Lake Tahoe',
      country: 'USA',
      lat: 39.0968,
      lng: -120.0324,
    },
    images: [
      'https://picsum.photos/seed/l4a/800/600',
      'https://picsum.photos/seed/l4b/800/600',
    ],
    amenities: ['wifi', 'kitchen', 'parking', 'ac'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.98,
    reviewCount: 89,
    reviews: [],
    houseRules: ['Leave the space as you found it'],
  },
  {
    id: 'l5',
    hostId: 'u1',
    title: 'Minimalist Tokyo Studio',
    description: 'Clean, efficient, and perfectly located. Experience the best of Shibuya from this quiet sanctuary.',
    pricePerNight: 85,
    type: 'ENTIRE_HOME',
    location: {
      address: 'Shibuya-ku',
      city: 'Tokyo',
      country: 'Japan',
      lat: 35.6762,
      lng: 139.6503,
    },
    images: [
      'https://picsum.photos/seed/l5a/800/600',
    ],
    amenities: ['wifi', 'ac', 'workspace'],
    maxGuests: 2,
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    rating: 4.65,
    reviewCount: 156,
    reviews: [],
    houseRules: ['No trash left behind'],
  }
];
